#!/usr/bin/env python
import os
import sys
import subprocess

modes = ['off', 'low', 'med', 'high']

def get_and_update_next_mode(direction):
    with open(os.path.expanduser('~/.config/kbd/setting'), 'r') as f:
        current_setting = f.read().replace('\n', '')

    idx = modes.index(current_setting)

    if direction == "up":
        new_mode = modes[min(len(modes) - 1, idx + 1)]
    elif direction == "down":
        new_mode = modes[max(0, idx - 1)]
    else:
        raise ValueError("Unknown argument")

    cp = subprocess.run(["asusctl", "--kbd-bright", new_mode], check=False)
    if cp.returncode == 0:
        with open(os.path.expanduser('~/.config/kbd/setting'), 'w') as f:
            f.write(new_mode)

    return new_mode

if __name__ == "__main__":
    get_and_update_next_mode(sys.argv[1])
