#! /usr/bin/env bash

if selection=$(fd --follow --hidden --exclude .git --color=always --type f |
               fzf ); then
  nohup "hires_wrapper" "xdg-open" "$selection" &>/dev/null &
  sleep 0.1
fi
