#!/usr/bin/env bash

pkill zoom; pkill slack; pkill spotify; pkill nm-applet; pkill blueman-applet; pkill onboard;
if [[ $@ = "--to-lowres" ]] 
then
    xrandr --output eDP1 --dpi 96
    sed -i "s/scaleFactor=2/scaleFactor=1/" $HOME/.config/zoomus.conf
    sed -i "s/Xft\.dpi: 192/Xft\.dpi: 96/" $HOME/.Xresources
    sed -i "s/Xcursor.size: 48/Xcursor.size: 24/" $HOME/.Xresources
    xrdb -merge $HOME/.Xresources
    sed -i "s/GDK_SCALE=2 GDK_DPI_SCALE=0.5/GDK_SCALE=1 GDK_DPI_SCALE=1/" $HOME/.local/bin/hires_wrapper
    sed -i "s/factor=2/factor=1/" $HOME/.local/bin/spotify_wrapper
elif [[ $@ = "--to-hires" ]] 
then
    xrandr --output eDP1 --dpi 192
    sed -i "s/scaleFactor=1/scaleFactor=2/" $HOME/.config/zoomus.conf
    sed -i "s/Xft\.dpi: 96/Xft\.dpi: 192/" $HOME/.Xresources
    sed -i "s/Xcursor.size: 24/Xcursor.size: 48/" $HOME/.Xresources
    xrdb -merge $HOME/.Xresources
    sed -i "s/GDK_SCALE=1 GDK_DPI_SCALE=1/GDK_SCALE=2 GDK_DPI_SCALE=0.5/" $HOME/.local/bin/hires_wrapper
    sed -i "s/factor=1/factor=2/" $HOME/.local/bin/spotify_wrapper
fi 
hires_wrapper zoom &
hires_wrapper slack &
hires_wrapper spotify_wrapper &
hires_wrapper nm-applet &
hires_wrapper blueman-applet &
i3-msg restart
onboard &
source $HOME/.fehbg
