#!/usr/bin/env bash

while IFS= read -r line; do
    echo $line
    if [[ $line = "dark" ]] 
    then
        kitty --override include="~/.config/kitty/themes/gruvbox_dark.conf" --single-instance
    elif [[ $line = "light" ]] 
    then
        kitty --override include="~/.config/kitty/themes/gruvbox_light.conf" --single-instance
    fi 
done < $HOME/.config/theme.yml
