#!/usr/bin/env bash

if [[ $@ = "--dark" ]] 
then
    # sed -i "s/include gruvbox_light.conf/include gruvbox_dark.conf/" $HOME/.config/kitty/kitty.conf
    kitty @ set-colors --all --configured "~/.config/kitty/themes/gruvbox_dark_hard.conf"
    ln -sf $HOME/.config/zathura/zathura_dark $HOME/.config/zathura/zathurarc
    echo 'dark' > $HOME/.config/theme.yml
elif [[ $@ = "--light" ]] 
then
    # sed -i "s/include gruvbox_dark.conf/include gruvbox_light.conf/" $HOME/.config/kitty/kitty.conf
    kitty @ set-colors --all --configured "~/.config/kitty/themes/gruvbox_light.conf"
    ln -sf $HOME/.config/zathura/zathura_light $HOME/.config/zathura/zathurarc
    echo 'light' > $HOME/.config/theme.yml
fi 
