#!/usr/bin/env bash

read -r TPdevice <<<"$(xinput | sed -nre '/[tT]rack[pP]oint/s/.*id=([0-9]*).*/\1/p' | sed -n 1p)"
state=$(xinput list-props "$TPdevice" | grep "Device Enabled" | grep -o "[01]$")

if [ "$state" -eq '1' ]; then
  xinput --disable "$TPdevice" && notify-send -i emblem-nowrite "Trackpoint" "Disabled"
else
  xinput --enable "$TPdevice" && notify-send -i input-touchpad "Trackpoint" "Enabled"
fi
