" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
" runtime! archlinux.vim

" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim80/vimrc_example.vim or the vim manual
" and configure vim to your own liking!

" do not load defaults if ~/.vimrc is missing
"let skip_defaults_vim=1

" :set virtualedit=onemore


set clipboard=unnamedplus

" Plugins
call plug#begin('~/.local/share/nvim/plugged')

" Gruvbox
Plug 'morhetz/gruvbox' 

" Vimtex
Plug 'lervag/vimtex'


call plug#end()

" Remapping
let mapleader=","
nmap <leader>w :w!<cr>

" Theme related
set termguicolors
set background=dark
let g:gruvbox_contrast_dark = "hard"
colorscheme gruvbox
syntax enable

" Tab and Spaces related
set tabstop=4
set softtabstop=4
set expandtab
set shiftwidth=4
set ai

" UI related
set number
set cursorline
filetype plugin on
filetype indent on
set wildmenu
set showmatch
set wildignore+=*/.git/*,*/.hg/*,/*/.svn/*,*/.DS_Store
set ruler
set cmdheight=1
set smartcase
set lazyredraw
set wrap
set showcmd

" Saves the file

" Searching related
set incsearch
set hlsearch
nnoremap <leader><space> :nohlsearch<CR>

