# Use Ubuntu as a base
FROM nparikh27/devbox:base

# Python installs
RUN pip3 install --user \
    tensorboardX \
    tqdm \
    opencv-python \
    numpy \
    tensorflow-gpu \
    torch \
    torchvision \
    scipy 

# Start shell
CMD zsh
