#!/usr/bin/env bash
# vim:fileencoding=utf-8:ft=bash:foldmethod=marker:foldlevel=0:colorcolumn=90

# -- {{{ setup
source "$HOME/.config/sketchybar/themes/colors.sh"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

FONT="FiraCode Nerd Font Mono"
PADDINGS=2

# Setting up the general bar appearance and default values
sketchybar --bar height=41                                            \
                     position=top                                     \
                     sticky=on                                        \
                     color=$bg0                                       \
                     border_width=1                                   \
                     border_color=$bg0                                \
                     y_offset=-2                                      \
                     margin=-2                                        \
                     notch_width=210                                  \
           --default updates=when_shown                               \
                     icon.font="$FONT:Retina:16.0"                    \
                     icon.color=$fg0                                  \
                     icon.padding_left=$PADDINGS                      \
                     icon.padding_right=$PADDINGS                     \
                     label.font="$FONT:SemiBold:12.0"                 \
                     label.color=$fg0                                 \
                     label.padding_left=$PADDINGS                     \
                     label.padding_right=$PADDINGS                    \
                     padding_right=$PADDINGS                          \
                     padding_left=$PADDINGS                           \
                     background.height=32                             \
                     popup.background.border_width=2                  \
                     popup.background.corner_radius=9                 \
                     popup.background.border_color=$faded_orange      \
                     popup.background.color=$bg0                      \
                     popup.background.shadow.drawing=on               \
           --add event screen_unlock "com.apple.screenIsUnlocked" 
# -- }}}

# -- {{{ spaces
MAIN_DISPLAY_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "0")
SECONDARY_DISPLAY_ICONS=("1̲ " "2̲" "3̲" "4̲" "5̲" "6̲")
SPACE_ICONS=("${MAIN_DISPLAY_ICONS[@]}" "${SECONDARY_DISPLAY_ICONS[@]}")

# Destroy space on right click, focus space on left click.
# New space by left clicking separator (>)
sketchybar --add event refresh_spaces

sid=0
spaces=()
for i in "${!SPACE_ICONS[@]}"
do
  sid=$(($i+1))
  sketchybar --add space space.$sid left                              \
             --set space.$sid associated_space=$sid                   \
                              script="$PLUGIN_DIR/space.sh"           \
                              width=20                                \
                              align=center                            \
                              label.drawing=off                       \
                              label.padding_left=0                    \
                              label.padding_right=0                   \
                              icon=${SPACE_ICONS[i]}                  \
                              icon.width=16                           \
                              icon.align=center                       \
                              icon.font="$FONT:SemiBold:11.0"         \
                              icon.color=$fg2                         \
                              icon.highlight_color=$fg2               \
                              icon.padding_left=1                     \
                              icon.padding_right=0                    \
                              background.color=$bg1                   \
                              background.corner_radius=5              \
                              background.height=20                    \
            --subscribe space.$sid mouse.clicked refresh_spaces 
done
# -- }}}
# -- {{{ calendar
sketchybar --add item calendar right                                  \
           --set calendar update_freq=21                              \
                       icon="󰥔"                                       \
                       icon.font="$FONT:Retina:18.0"                  \
                       icon.padding_right=4                           \
                       icon.color=$neutral_blue                       \
                       icon.y_offset=2                                \
                       label.y_offset=1                               \
                       label.font="$FONT:SemiBold:12.0"               \
                       label.color=$neutral_blue                      \
                       label.padding_right=8                          \
                       background.color=$faded_blue                   \
                       background.height=2                            \
                       background.padding_right=6                     \
                       background.y_offset=-9                         \
                       script="$PLUGIN_DIR/calendar.sh"               \
                       icon.padding_left=0                            \
                       label.padding_right=1                          \
            --subscribe calendar system_woke screen_unlock 
# -- }}}
# -- {{{ battery
sketchybar --add item battery right                                   \
           --set battery update_freq=60                               \
                       icon.font="$FONT:Retina:11.5"                  \
                       icon.padding_right=3                           \
                       icon.color=$neutral_yellow                     \
                       icon.y_offset=2                                \
                       label.y_offset=1                               \
                       label.font="$FONT:SemiBold:12.0"               \
                       label.color=$neutral_yellow                    \
                       label.padding_right=8                          \
                       background.color=$faded_yellow                 \
                       background.height=2                            \
                       background.y_offset=-9                         \
                       background.padding_right=8                     \
                       script="$PLUGIN_DIR/battery.sh"                \
                       icon.padding_left=0                            \
                       label.padding_right=1                          \
            --subscribe battery system_woke screen_unlock mouse.entered

# -- }}}
# -- {{{ wifi
sketchybar --add item wifi_speed_mbps right                           \
           --set wifi_speed_mbps                                      \
                      icon.drawing=off                                \
                      label.padding_right=6                           \
                      width=0                                         \
                      label.y_offset=3                                \
                      label.font="$FONT:SemiBold:7.0"                 \
                      label.color=$bright_red

sketchybar --add graph wifi_speed right 60                            \
sketchybar --set wifi_speed update_freq=1                             \
                            graph.color="0x77${neutral_red:0-6}"      \
                            graph.fill_color="0x77${neutral_red:0-6}" \
                            graph.line_width=0.5                      \
                            label.drawing=off                         \
                            icon.drawing=off                          \
                            background.padding_right=8                \
                            background.drawing=on                     \
                            background.height=22.5                    \
                            background.padding_left=0                 \
                            background.color=$transparent             \
                            script="$PLUGIN_DIR/wifi_speed.sh"        \
            --subscribe wifi_speed mouse.clicked screen_unlock system_woke

sketchybar --add item wifi right                                      \
           --set wifi icon.font="$FONT:Retina:22.0"                   \
                      icon.padding_right=1                            \
                      icon.color=$neutral_orange                      \
                      icon.y_offset=1                                 \
                      label.y_offset=1                                \
                      label.font="$FONT:SemiBold:12.0"                \
                      label.color=$neutral_orange                     \
                      background.color=$faded_orange                  \
                      background.height=2                             \
                      background.y_offset=-9                          \
                      background.padding_right=1                      \
                      script="$PLUGIN_DIR/wifi.sh"                    \
                      icon.padding_left=0                             \
                      label.padding_right=1                           \
                      label.padding_left=1                            \
            --subscribe wifi mouse.clicked 
# -- }}}
# -- {{{ bluetooth
sketchybar --add item bluetooth right                                 \
           --set bluetooth update_freq=60                             \
                       icon.font="$FONT:Retina:14.0"                  \
                       icon.padding_right=1                           \
                       icon.padding_left=2                            \
                       icon.color=$neutral_aqua                       \
                       icon.y_offset=2                                \
                       label.y_offset=1                               \
                       label.font="$FONT:SemiBold:12.0"               \
                       label.color=$neutral_aqua                      \
                       label.padding_right=0                          \
                       label.padding_left=1                           \
                       background.color=$faded_aqua                   \
                       background.height=2                            \
                       background.y_offset=-9                         \
                       background.padding_right=8                     \
                       script="$PLUGIN_DIR/bluetooth.sh"              \
            --subscribe bluetooth mouse.clicked
# -- }}}
# -- {{{ volume
sketchybar --add slider volume e                                      \
           --set volume icon="󰖀"                                      \
                 icon.drawing=on                                      \
                 icon.y_offset=1                                      \
                 icon.font="$FONT:Retina:17.0"                        \
                 label.drawing=off                                    \
                 slider.background.corner_radius=2                    \
                 slider.background.height=7                           \
                 slider.background.border_width=2                     \
                 slider.background.y_offset=0                         \
                 slider.knob="󱋱"                                      \
                 slider.knob.y_offset=1                               \
                 slider.knob.font="$FONT:Retina:11.0"                 \
                 slider.width=70                                      \
                 slider.percentage=40                                 \
                 background.height=2                                  \
                 background.y_offset=-9                               \
                 background.padding_right=8                           \
                 background.padding_left=8                            \
                 icon.color=$fg3                                      \
                 label.color=$fg3                                     \
                 slider.background.border_color=$bg0                  \
                 slider.background.color=$bg0                         \
                 slider.highlight_color=$fg3                          \
                 slider.knob.color=$fg3                               \
                 background.color=$fg4                                \
                 script="$PLUGIN_DIR/volume.sh"                       \
           --subscribe volume volume_change mouse.clicked system_woke screen_unlock
# -- }}}

# -- {{{ cleanup
sketchybar --hotload true
# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

# Force triggers
sleep 1 && sketchybar --trigger refresh_spaces
sleep 1 && sketchybar --trigger refresh_focus
# -- }}}
